services:
  bazarr:
    image: ${DOCKER_MIRROR}lscr.io/linuxserver/bazarr:${VERSION}
    container_name: bazarr
    ports:
      - "${TRIM_SERVICE_PORT}:6767"
    volumes:
      - ${TRIM_PKGVAR}/config:/config
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
