services:
  redis:
    image: ${DOCKER_MIRROR}docker.io/library/redis:7-alpine
    container_name: paperless-ngx-redis
    restart: unless-stopped

  paperless:
    image: ${DOCKER_MIRROR}ghcr.io/paperless-ngx/paperless-ngx:${VERSION}
    container_name: paperless-ngx
    depends_on:
      - redis
    ports:
      - "${TRIM_SERVICE_PORT}:8000"
    volumes:
      - ${TRIM_PKGVAR}/data:/usr/src/paperless/data
      - ${TRIM_PKGVAR}/media:/usr/src/paperless/media
      - ${TRIM_PKGVAR}/export:/usr/src/paperless/export
      - ${TRIM_PKGVAR}/consume:/usr/src/paperless/consume
    environment:
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_DBENGINE=sqlite
      - PAPERLESS_PORT=8000
      - PAPERLESS_URL=http://localhost:${TRIM_SERVICE_PORT}
      - TZ=Asia/Shanghai
    restart: unless-stopped
