services:
  homarr:
    image: ${DOCKER_MIRROR}ghcr.io/homarr-labs/homarr:${VERSION}
    container_name: homarr
    ports:
      - "${TRIM_SERVICE_PORT}:7575"
    volumes:
      - ${TRIM_PKGVAR}/config:/appdata
      - ${TRIM_PKGVAR}/icons:/icons
    environment:
      - TZ=Asia/Shanghai
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    restart: unless-stopped
