services:
  actual-budget:
    image: ${DOCKER_MIRROR}docker.io/actualbudget/actual-server:${VERSION}
    container_name: actual-budget
    ports:
      - "${TRIM_SERVICE_PORT}:5006"
    volumes:
      - ${TRIM_PKGVAR}/data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
