services:
  stirling-pdf:
    image: ${DOCKER_MIRROR}docker.io/stirlingtools/stirling-pdf:${VERSION}
    container_name: stirling-pdf
    ports:
      - "${TRIM_SERVICE_PORT}:8080"
    volumes:
      - ${TRIM_PKGVAR}/config:/configs
      - ${TRIM_PKGVAR}/data:/customFiles
    environment:
      - TZ=Asia/Shanghai
      - DOCKER_ENABLE_SECURITY=false
    restart: unless-stopped
