services:
  homepage:
    image: ${DOCKER_MIRROR}ghcr.io/gethomepage/homepage:${VERSION}
    container_name: homepage
    ports:
      - "${TRIM_SERVICE_PORT}:3000"
    volumes:
      - ${TRIM_PKGVAR}/config:/app/config
      - ${TRIM_PKGVAR}/icons:/app/public/icons
    environment:
      - TZ=Asia/Shanghai
      - HOMEPAGE_ALLOWED_HOSTS=*
    restart: unless-stopped
