#!/bin/bash
FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"

is_docker_running() {
    if [ ! -f "$FILE_PATH" ]; then
        return 1
    fi

    docker inspect paperless-ngx 2>/dev/null | grep -q "\"Status\": \"running\"," || exit 1
}

case $1 in
start) exit 0 ;;
stop) exit 0 ;;
status) if is_docker_running; then exit 0; else exit 3; fi ;;
*) exit 1 ;;
esac
