services:
  photoprism:
    image: ${DOCKER_MIRROR}docker.io/photoprism/photoprism:${VERSION}
    container_name: photoprism
    ports:
      - "${TRIM_SERVICE_PORT}:2342"
    volumes:
      - ${TRIM_PKGVAR}/storage:/photoprism/storage
      - ${TRIM_PKGVAR}/originals:/photoprism/originals
    environment:
      - TZ=Asia/Shanghai
      - PHOTOPRISM_ADMIN_PASSWORD=admin
      - PHOTOPRISM_SITE_URL=http://localhost:${TRIM_SERVICE_PORT}
    restart: unless-stopped
