services:
  ollama:
    image: ${DOCKER_MIRROR}docker.io/ollama/ollama:${VERSION}
    container_name: ollama
    ports:
      - "${TRIM_SERVICE_PORT}:11434"
    volumes:
      - ${TRIM_PKGVAR}/data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - TZ=Asia/Shanghai
    restart: unless-stopped
