services:
  maxkb:
    image: ${DOCKER_MIRROR}docker.io/1panel/maxkb:v${VERSION}
    container_name: maxkb
    ports:
      - "${TRIM_SERVICE_PORT}:8080"
    volumes:
      - ${TRIM_PKGVAR}/data:/opt/maxkb
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
