services:
  uptime-kuma:
    image: ${DOCKER_MIRROR}docker.io/louislam/uptime-kuma:${VERSION}
    container_name: uptime-kuma
    ports:
      - "${TRIM_SERVICE_PORT}:3001"
    volumes:
      - ${TRIM_PKGVAR}/config:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
