services:
  jellyseerr:
    image: ${DOCKER_MIRROR}docker.io/fallenbagel/jellyseerr:${VERSION}
    container_name: jellyseerr
    ports:
      - "${TRIM_SERVICE_PORT}:5055"
    volumes:
      - ${TRIM_PKGVAR}/config:/app/config
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
