services:
  mealie:
    image: ${DOCKER_MIRROR}ghcr.io/mealie-recipes/mealie:${VERSION}
    container_name: mealie
    ports:
      - "${TRIM_SERVICE_PORT}:9000"
    volumes:
      - ${TRIM_PKGVAR}/data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_SIGNUP=true
      - BASE_URL=http://localhost:${TRIM_SERVICE_PORT}
    restart: unless-stopped
