services:
  homeassistant:
    image: ${DOCKER_MIRROR}lscr.io/linuxserver/homeassistant:${VERSION}
    container_name: homeassistant
    network_mode: host
    privileged: true
    volumes:
      - ${TRIM_PKGVAR}/config:/config
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Asia/Shanghai
      - PUID=${TRIM_UID}
      - PGID=${TRIM_GID}
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
    restart: unless-stopped
